name: Raspberry Pi Distcc
on: [push]
jobs:
  Build-Image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Build Image
        run: |
          docker build . -t herman818/raspberry-pi-distcc:lastest

